### ISSUE TITLE
Multi-colored sticky notes

### ISSUE THREAD

**Issue by mastermajorman** [MelkeyOSS/astrostation#197]
![image](https://user-images.githubusercontent.com/56801158/180663306-4bcff3e9-7d8a-420a-8185-445a39fcb5da.png)

**Comment by mastermajorman** [comment]
> I'd like to work on this. I'm also open to working with others on this issue if anyone would like to 😃

Feel free. I've been sitting on this for a while. We could have something like this but it's up to you!
![image](https://user-images.githubusercontent.com/56801158/225768046-f1d08c98-6a7e-40b1-a03c-87492276609e.png)
![image](https://user-images.githubusercontent.com/56801158/225768077-8f119dfc-d704-413d-b12b-d5a505e51cb9.png)

**Comment by herropaul** [comment]
> > I'd like to work on this. I'm also open to working with others on this issue if anyone would like to 😃
> 
> Feel free. I've been sitting on this for a while. We could have something like this but it's up to you! ![image](https://user-images.githubusercontent.com/56801158/225768046-f1d08c98-6a7e-40b1-a03c-87492276609e.png) ![image](https://user-images.githubusercontent.com/56801158/225768077-8f119dfc-d704-413d-b12b-d5a505e51cb9.png)

Honestly I like that idea better than what I had in mind haha. Originally I was thinking an onHover over the stickynote button that would display the colors. I'm gonna look into trying ur idea out
