### ISSUE TITLE
Add GitHub repo to dashboard

### ISSUE THREAD

**Issue by royanger** [MelkeyOSS/astrostation#229]
The project is now OSS, and we should make that obvious and link to the repo. Perhaps a button beside Donate.

**Comment by devharsh007** [comment]
Please assign this issue to me. I would like to work on it.

**Comment by Melkeydev** [comment]
@devharsh007 I assigned the task to you

**Comment by royanger** [comment]
@devharsh007 We have at least one other person interested in this. If you would like to handle this, please submit your PR in within 2 days. Thanks!

**Comment by devharsh007** [comment]
Sorry for the delay. I'll update you till 2moro.

**Comment by madeleine-patience** [comment]
Ill grab this @royanger @Melkeydev

**Comment by royanger** [comment]
Merged into staging with https://github.com/MelkeyOSS/astrostation/pull/239
