### ISSUE TITLE
Task Tracker causes horizontal and vertical overflow, while the other widgets do not 

### ISSUE THREAD

**Issue by Melkeydev** [MelkeyOSS/astrostation#244]
![image](https://user-images.githubusercontent.com/53410236/227748543-0df6a82d-5aa5-4071-8b1e-b7580ced55f8.png)

**Comment by justnat3** [comment]
I cannot reproduce this on chrome, or firefix

**Comment by zemzelett** [comment]
I've found the cause for this, i'm just not quite sure what the root cause is. Can i take this issue?
