### ISSUE TITLE
Change z-index implementation for drag and drop

### ISSUE THREAD

**Issue by royanger** [MelkeyOSS/astrostation#245]
Currently when dragging a widget the z-index just scales.

New behaviour:

- add default new z-index of 50 in a new store
- when a widget is dragged, grab z-index from store, increment it by 1 and use for z-index
- after incrementation/drag, update store with new number (Ie, 51 on first widget drag, 52 on second, etc)

**Comment by Melkeydev** [comment]
i feel i should be responsible for fixing this one lol

**Comment by royanger** [comment]
No

**Comment by justnat3** [comment]
This function is run **as** a d-card(draggable-card) is held by the cursor. I am looking for some guidance here, this still seems wrong- but here is what I have so far. Not entirely sure if this is any better than the original- elements is only 7 elements in length in my testing.

Original Implementation

```js
 function trackPosition() {
    setZ(++int);
  }
```

Refactored 

```js
 // FIXME: change name
  function getOnTop() {
    const elements = document.querySelectorAll(".react-draggable");
    let draggable = dref.current;

    if (typeof draggable === "object" && draggable !== null && "getBoundingClientRect" in draggable) {
      // @ts-ignore
      draggable_rect = draggable.getBoundingClientRect();
    }

    elements.forEach(node => {
      // @ts-ignore
      const node_rect = node.getBoundingClientRect();

      // @ts-ignore
      if ((node_rect.width, node_rect.height) === (draggable.width, draggable.height)) return;

      if (
        node_rect.bottom >= draggable_rect.top &&
        node_rect.right >= draggable_rect.left &&
        node_rect.left <= draggable_rect.right &&
        node_rect.top <= draggable_rect.bottom
      ) {
        const node_z = Number(window.getComputedStyle(node).zIndex);
        const dref_z = Number(window.getComputedStyle(draggable).zIndex);
        if (node_z > dref_z) {
          setZ(node_z + 1);
        }
      }
    });
  }
```

**Comment by justnat3** [comment]
@Melkeydev @royanger @Hacksore

**Comment by justnat3** [comment]
I did some profiling, here are the profiles. 

[My Implementation](https://share.firefox.dev/42Jf0a7)
[Original](https://share.firefox.dev/42NpHIQ)
 
I imagine there is a better more optimal way, but I am unsure of it right now.

**Comment by justnat3** [comment]
> Currently when dragging a widget the z-index just scales.
> 
> New behaviour:
> 
>     * add default new z-index of 50 in a new store
> 
>     * when a widget is dragged, grab z-index from store, increment it by 1 and use for z-index
> 
>     * after incrementation/drag, update store with new number (Ie, 51 on first widget drag, 52 on second, etc)

lel. did not see this. seems reasonable.
