### ISSUE TITLE
License for photo backgrounds and the 'Chill Music' widget

### ISSUE THREAD

**Issue by eraychumak** [MelkeyOSS/astrostation#247]
I haven't checked all of them, nor am I sure on the aquiring process of the photos, but for example with 'Lofi Girl', the app cannot use it: https://lofigirl.com/pages/use-the-music

![image](https://user-images.githubusercontent.com/44278658/228017975-11c47b05-9cac-4f7b-87e0-8d957af38cde.png)

Also, I don't think we're crediting the use of the lofi music properly, definitely needs to be checked out.

**Comment by royanger** [comment]
This is major issue, particularly with the app now OSS. We should review all images and music and either credit as required or replace.
