### ISSUE TITLE
Allow spotify playlist to be persisted to local storage

### ISSUE THREAD

**Issue by Hacksore** [MelkeyOSS/astrostation#253]
I would like to be able to save my playlist to local storage so that I can always have my [BANGERS 🔥](https://open.spotify.com/playlist/3tLfoRdkhPffpb9Gnr0BrM?si=8cd4fe2aa0fb4a76)

Should be a simple task.

**Comment by royanger** [comment]
A banger improvement (not to be confused with Hacksore's non banger playlist) would be store up to 5 or 10 and provide a dropdown to let the user choose from those recent playlists.

**Comment by lak7** [comment]
Hello! I would like to work on this issue. Can I be assigned to it, please?

**Comment by Hacksore** [comment]
@lak7 looks like @cimok2000 already has a PR open #258

**Comment by cimok2000** [comment]
hi sorry yeah I have been working on this, I've been super busy the past two weeks but I'll get something pulled soon 😎

**Comment by Hacksore** [comment]
I'd suggest folks follow the open [PR](https://github.com/MelkeyOSS/astrostation/pull/258) for updates, closing this issue to get it out of my queue.
