### ISSUE TITLE
Discussion: Kanban board widget design & UX considerations

### ISSUE THREAD

**Issue by trobonox** [MelkeyOSS/astrostation#266]
![screenshot_kanban](https://user-images.githubusercontent.com/57040351/230430236-878dc8b6-90d3-4ea9-aac0-443df28244a8.png)

This is the current state of the Kanban widget I am working on to be implemented into Astrostation.
I've run into some questions I can't answer myself with certainty, so I'm putting them in this issue for discussion, as @royanger suggested.

Here's the questions:
1. **General question**: should I open a draft PR for the implementation I have so far?
2. Currently the X button on the cards in the columns instantly deletes the tasks. Do we prefer speed or should I rather implement a confirmation dialog for this destructive action?
3. How would we go about editing a task?Is it enough if there's a pencil icon next to the X icon which turns the text of a card into an input where you will be able to directly edit the task? Or would we want a little modal or floating menu for this?
4. When the content of a column overflows because of too many cards, both the title and the button to add a new task scroll with the cards (which means that the title disappears when scrolling down for example). In my opinion it makes sense to pin at least the title, but should we also make the "Add Task" button permanently visible or do we keep the extra screen real estate and let it scroll?

Would really appreciate some opinions on these, if you believe these are not that important I can just go ahead and implement whatever I think works best and we improve everything progressively.

**Comment by Melkeydev** [comment]
```
General question: should I open a draft PR for the implementation I have so far?
``` 
Yes please!

```
Currently the X button on the cards in the columns instantly deletes the tasks. Do we prefer speed or should I rather implement a confirmation dialog for this destructive action?
```
I am okay with either or, but i think if you want you can add just an alert function that adds a confirmation. I think @justnat3 is working on a modal replacement for all the alerts

```
How would we go about editing a task?Is it enough if there's a pencil icon next to the X icon which turns the text of a card into an input where you will be able to directly edit the task? Or would we want a little modal or floating menu for this?
```
I think just how we edit tasks right now can suffice - just an edit icon that lets the user change the text


```
When the content of a column overflows because of too many cards, both the title and the button to add a new task scroll with the cards (which means that the title disappears when scrolling down for example). In my opinion it makes sense to pin at least the title, but should we also make the "Add Task" button permanently visible or do we keep the extra screen real estate and let it scroll?
```
I agree that i think it is only important to pin the title. I think it should be okay if users scroll

**Comment by royanger** [comment]
> 2\. Currently the X button on the cards in the columns instantly deletes the tasks. Do we prefer speed or should I rather implement a confirmation dialog for this destructive action?

I would prefer instant 'delete' but delete leaving the data in place but hiding them. That would require some form of undelete mode though, so this might not be feasible.

> 3\. Is it enough if there's a pencil icon next to the X icon which turns the text of a card into an input where you will be able to directly edit the task?

This feels like the best solution.

> 4\. When the content of a column overflows because...

How about adding a second 'add task' button that is just a + located in the title bar on the right side?

Other thoughts:

- Should this be drag-to-resize like the Twitch widget?
- When there are enough tasks to overflow, and user clicks to start adding a task the 'Add Task' and 'Cancel' are both off the screen.
- To increase useful space maybe ditch the box around the column and let the tasks be a little wider. See attached screen shot (need a touch of padding on the right for the scroll bar if we go this route). 

![image](https://user-images.githubusercontent.com/24333362/230696026-f507c446-2bb4-4ffa-aee0-08dec73536fb.png)

**Comment by trobonox** [comment]
Closing this since we've figured out all of these points and everything else can be discussed on the actual PR.
