### ISSUE TITLE
Default quote widget position overlaps task tracker widget

### ISSUE THREAD

**Issue by mechakin** [MelkeyOSS/astrostation#274]
![Screenshot 2023-04-11 093258](https://user-images.githubusercontent.com/58408370/231179450-2dfde851-447e-495c-b4e8-90607128b071.png)

**Comment by Zukauskas** [comment]
Same for me. Seems that default position is wrong. But I see changes to default positions in #227 , so just need to wait? :)

**Comment by Melkeydev** [comment]
I will be picking this up since it is a simple fix
